### ISSUE TITLE
Doesn't work on WoW Classic

### ISSUE THREAD

**Issue by zingmars** [Nighthawk42/wow_bejeweled#7]
When opened, in WoW Classic, you get the Bejeweled logo but nothing else - The menu is grayed out and nothing happens. Also the games stops accepting keyboard inputs (like WASD) while this window is open.

**Comment by zingmars** [comment]
Hm, oddly enough [Peggle](https://github.com/adamz01h/wow_peggle) got broken after loading this addon. I can't actually load either now (Peggle worked just fine before this was loaded) and I'm getting a warning about too many LUA errors when either window is open.

**Comment by Nighthawk42** [comment]
Check the latest release on the Classic branch, it should function correctly now.

**Comment by zingmars** [comment]
Ok, it works but there's still the issue of the game not accepting any input while the bejeweled window is open. Also, when there's a popup (which for some reason sometimes appears at the bottom of the screen and is barely noticeable) it's impossible to close the bejeweled window.

**Comment by Nighthawk42** [comment]
Odd, I haven't seen that behavior. I know the game doesn't like to start sometimes. As for the window not closing that's a new issue. I'll see what I can do, Classic has a lot of UI changes and I'm not actively trying to keep it updated due to IRL time constraints (I'm not playing the game either). I was really hoping that the 8.2 build would work with minimal changes, but you know Blizzard. Keep an eye on the other forks as well as they might update ahead of my releases.
